version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cms
    ports: ["5432:5432"]
    volumes: [ "db_data:/var/lib/postgresql/data" ]
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
  api:
    build: ./apps/api
    env_file: ./apps/api/.env.example
    depends_on: [ db, redis ]
    ports: ["3000:3000"]
  web:
    build: ./apps/web
    environment:
      PUBLIC_API_URL: http://api:3000/api
    depends_on: [ api ]
    ports: ["4321:4321"]
volumes:
  db_data:
